# Generated by Django 5.1.5 on 2025-01-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id_tipo_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id_verificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('verificacion', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_os', models.ForeignKey(db_column='id_os', on_delete=django.db.models.deletion.CASCADE, to='app.organismosectorial')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField(null=True)),
                ('termino', models.DateTimeField(null=True)),
                ('estado_avance', models.CharField(blank=True, max_length=255, null=True)),
                ('organismos', models.ManyToManyField(through='app.OrganismoPlan', to='app.organismosectorial')),
            ],
        ),
        migrations.AddField(
            model_name='organismoplan',
            name='id_plan',
            field=models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='app.plan'),
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('referencia_pda', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=100)),
                ('indicador', models.TextField(max_length=2000)),
                ('formula_de_calculo', models.TextField(max_length=2000)),
                ('frecuencia_reporte', models.CharField(choices=[('ANUAL', 'Anual'), ('UNICA', 'Unica'), ('CADA_5_ANIOS', 'Cada 5 años')], default='ANUAL', max_length=30)),
                ('tipo_de_dato_a_validar', models.CharField(blank=True, max_length=100, null=True)),
                ('id_os', models.ForeignKey(db_column='id_os', on_delete=django.db.models.deletion.CASCADE, to='app.organismosectorial')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='app.plan')),
                ('id_tipo_medida', models.ForeignKey(db_column='id_tipo_medida', on_delete=django.db.models.deletion.CASCADE, to='app.tipomedida')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medida', models.ForeignKey(db_column='id_medida', on_delete=django.db.models.deletion.CASCADE, to='app.medida')),
                ('id_verificacion', models.ForeignKey(db_column='id_verificacion', on_delete=django.db.models.deletion.CASCADE, to='app.verificacion')),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='verificaciones',
            field=models.ManyToManyField(through='app.VerificacionMedida', to='app.verificacion'),
        ),
    ]
