# Generated by Django 5.1.5 on 2025-03-28 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='organismosectorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organismosectorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipomedida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipomedida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='MedidaReportada',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_medida_reportada', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(help_text='Resultado de la medida aplicada.', max_length=50)),
                ('estado', models.CharField(choices=[('VERIFICACION_PENDIENTE', 'Verificación pendiente'), ('VERIFICADA', 'Verificada'), ('RECHAZADA', 'Rechazada')], default='VERIFICACION_PENDIENTE', max_length=30)),
                ('id_medida', models.ForeignKey(db_column='id_medida', help_text='Id de la medida a resportar.', on_delete=django.db.models.deletion.CASCADE, to='app.medida')),
                ('id_os', models.ForeignKey(db_column='id_os', help_text='Id del Organismo Sectorial que está informando.', on_delete=django.db.models.deletion.CASCADE, to='app.organismosectorial')),
                ('id_usuario', models.ForeignKey(help_text='Id Usuario de django.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
